# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Aybüke Erata
tagline:          'Kişisel Web Sitem'
description:      'Bazı ufak notlar'
url:              https://aybukeerata.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Aybüke Erata'
  url:            https://twitter.com/...

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom vars
version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/aybukeerata7
  
disqus:
  shortname: aybukeerata

google_analytics: 'UA-113478991-1'

# languages: &languages
#  - name: 'Türkçe'
#    value: 'tr'
#  - name: 'İngilizce'
#    value: 'en'  
    
prose:
  rooturl: "_posts"
  siteurl: "https://erata.github.io/"
  relativeLinks: 'https://erata.github.io/links.jsonp'
  media: 'assets/media'
  #ignore: ['CNAME', '_config.yml', '*.json', '.gitignore', 'readme.md', '*.xml', 'admin.html']
  metadata:
    _posts:
    #  - name: "lang"
    #    field:
    #      element: "select"
    #      label: "Select language"
    #      placeholder: "Tükçe"
    #      options: *languages
    #      selected: "tr"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish now"
          help: "Keep this unchecked if you do not want to   publish the article right now"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Enter title of the Article"
          placeholder: "Enter Title"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: "CURRENT_DATETIME"
   #   - name: "author"
   #     field:
   #       element: "hidden"
   #       value: "Aybüke Erata"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Category"
          placeholder: "Add Category"
          options:
            - name: "Bilgi Güvenliği"
              value: "Bilgi Güvenliği"
            - name: "Linux/Bash Script"
              value: "Linux/Bash Script"  
            - name: "Mobil Programlama"
              value: "Mobil Programlama"
            - name: "Diğer"
              value: "Diğer"  
          alterable: true
     #   field:
     #     element: "hidden"
     #     value: "blog"
     #     alterable: "true"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Add Tags"
          options:
            - name: "Android"
              value: "Android"
            - name: "KALI"
              value: "KALI"  
            - name: "Program İnceleme"
              value: "Program İnceleme"   
          alterable: true
      - name: "excerpt_separator"
        field:
          element: "text"
          value: "<!--more-->"
